# SuperMandi 2.0 — Prod Profile

# Logging
logging.level.com.supermandi=INFO
logging.level.org.springframework.data.mongodb=WARN

# Hide error details from clients
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
